version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbpass
      MYSQL_DATABASE: hackernews
      MYSQL_USER: hackernews
      MYSQL_PASSWORD: dbpass
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql
